### ISSUE TITLE
Zones not showing up in dev

### ISSUE THREAD

**Issue by shifuoogway** [zacharyrs/ha-melview#15]
Could not find the zones on the temperature card using the dev code. 

![image](https://user-images.githubusercontent.com/91397155/135175183-3d3a416c-dfa4-4da4-80c8-48a835420a9c.png)

**Comment by zacharyrs** [comment]
@shifuoogway - the zone support is set up as a separate component, they should show as switches I think.

Unfortunately I don't have zones to test it myself - and the implementation was done by @MinaHany not myself.

**Comment by shifuoogway** [comment]
@zacharyrs, thanks for the clue. Working after repeating the credentials for the switch component...

switch:
  - platform: melview
    email: MY_EMAIL@gmail.com
    password: MY_PASSWORD
    local: yes
