### ISSUE TITLE
New install

### ISSUE THREAD

**Issue by icepicknz** [zacharyrs/ha-melview#16]
Hi,

Very new to HA, but have used SmartThings for 5 years or more.

Just installed HA OS on a RPI4
Have put files in /config/custom_components/melview 

Have added following the configuration.yaml
climate:
  - platform: melview
    email: user@email
    password: pass@word
    local: yes

I get the following error with configuration validation:
Platform error climate.melview - Integration 'melview' not found

When trying to restart via web GUI I get the following:
Failed to call service homeassistant/restart. The system cannot restart because the configuration is not valid: Platform error climate.melview - Integration 'melview' not found.

Any help would be appreciated

**Comment by zacharyrs** [comment]
Hey @icepicknz,

It sounds like either the component is failing to load, or is not recognised at all.

Can you double-check the permissions of the `melview` folder (is it accessible to the user/group running homeassistant?).

If that's not an issue, can you clarify how you put the files in that folder?
Did you `git clone`?

**Comment by icepicknz** [comment]
Thanks for the prompt reply.

The files are 755

I located configuration.yaml in /config
I then created custom_components & melview within.
I downloaded the master.zip and unzipped the files into melview
I then chmod 755 the files.

melview.py along with climate.py is in /config/custom_components/melview

**Comment by zacharyrs** [comment]
Hey @icepicknz,

That's definitely a bit odd...

What are the permissions on the `custom_components` and `melview` directories?

Could you also see if there's anything in the log?

**Comment by icepicknz** [comment]
`[core-ssh config]$ ls -al
total 888
drwxr-xr-x    8 root     root          4096 Oct 10 18:14 .
drwxr-xr-x    1 root     root          4096 Oct 10 18:19 ..
-rw-r--r--    1 root     root             9 Oct 10 17:27 .HA_VERSION
drwxr-xr-x    2 root     root          4096 Oct 10 17:27 .cloud
drwxr-xr-x    2 root     root          4096 Oct 10 18:17 .storage
-rw-r--r--    1 root     root             2 Oct 10 17:27 automations.yaml
drwxr-xr-x    4 root     root          4096 Oct 10 17:27 blueprints
-rw-r--r--    1 root     root           366 Oct 10 18:11 configuration.yaml
drwxr-xr-x    3 root     root          4096 Oct 10 17:51 custom_components
drwxr-xr-x    2 root     root          4096 Oct 10 17:27 deps
-rw-r--r--    1 root     root             0 Oct 10 17:27 groups.yaml
-rw-r--r--    1 root     root           687 Oct 10 18:19 home-assistant.log
-rw-r--r--    1 root     root          9379 Oct 10 18:10 home-assistant.log.1
-rw-r--r--    1 root     root             0 Oct 10 18:14 home-assistant.log.fault
-rw-r--r--    1 root     root        221184 Oct 10 18:12 home-assistant_v2.db
-rw-r--r--    1 root     root         32768 Oct 10 18:18 home-assistant_v2.db-shm
-rw-r--r--    1 root     root        589192 Oct 10 18:18 home-assistant_v2.db-wal
-rw-r--r--    1 root     root             0 Oct 10 17:27 scenes.yaml
-rw-r--r--    1 root     root             0 Oct 10 17:27 scripts.yaml
-rw-r--r--    1 root     root           161 Oct 10 17:27 secrets.yaml
drwxr-xr-x    2 root     root          4096 Oct 10 17:27 tts

[core-ssh config]$ ls -al custom_components/
total 12
drwxr-xr-x    3 root     root          4096 Oct 10 17:51 .
drwxr-xr-x    8 root     root          4096 Oct 10 18:14 ..
drwxrwxrwx    2 root     root          4096 Oct 10 17:37 melview

[core-ssh config]$ ls -al custom_components/melview/
total 44
drwxrwxrwx    2 root     root          4096 Oct 10 17:37 .
drwxr-xr-x    3 root     root          4096 Oct 10 17:51 ..
-rwxr-xr-x    1 root     root           711 Oct 10 17:37 README.md
-rwxr-xr-x    1 root     root            31 Oct 10 17:37 __init__.py
-rwxr-xr-x    1 root     root          8039 Oct 10 17:37 climate.py
-rwxr-xr-x    1 root     root           319 Oct 10 17:37 manifest.json
-rwxr-xr-x    1 root     root         14149 Oct 10 17:37 melview.py

[core-ssh config]$ ps -a
PID   USER     TIME  COMMAND
    1 root      0:00 s6-svscan -t0 /var/run/s6/services
   35 root      0:00 s6-supervise s6-fdholderd
  463 root      0:00 s6-supervise sshd
  464 root      0:00 s6-supervise ttyd
  467 root      0:00 sshd: /usr/sbin/sshd -D -e [listener] 0 of 10-100 startups
  468 root      0:00 ttyd -p 8099 tmux -u new -A -s homeassistant bash -l
  509 root      0:00 sshd: root@pts/0
  511 root      0:00 -bash
  529 root      0:00 ps -a

`

**Comment by icepicknz** [comment]
And here is my configuration.yaml

`# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

climate:
  - platform: melview
    email: user@email
    password: pass@word
    local: yes

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
`

**Comment by zacharyrs** [comment]
Nothing there stands out to me, unfortunately.

---

> Odd, after a reboot it seems to be working; just verifying now and then will close case once confirmed

I was just about to suggest a reboot, but it looks like you got there ahead of me!

**Comment by icepicknz** [comment]
Yup, I suspect because there was no custom_components folder when it booted up, it didn't know about it and kept erroring, after a reboot all was good :) thanks again for prompt response and the good work you've put into this :)
