### ISSUE TITLE
ClimateDevice is depricated

### ISSUE THREAD

**Issue by gazelle-hub** [zacharyrs/ha-melview#3]
HI there,

Not sure if you've seen this or not but I'm getting an error the logs for this component saying:

"ClimateDevice is deprecated, modify MelViewClimate to extend ClimateEntity".

Hasn't caused an issue yet but I guess it could on future versions.

I'm running HA 0.110.0.

Love this component btw, you've done a great job.

**Comment by zacharyrs** [comment]
Thanks for the heads up!

I haven't updated my install recently, so that's probably why I haven't seen that...

I'm quite busy these next couple of weeks (uni etc.), but I'll hopefully make any changes necessary after that.

**Comment by dpDesignz** [comment]
Did you manage to get this fixed? I'm having the same error spat at me. I'd do a pull to fix it myself but I have no idea when it comes to python sorry

**Comment by zacharyrs** [comment]
I haven't touched that yet - been a bit busy with university, plus it still runs so I figured a fix wasn't a necessity yet!

I'll take a look at it over the weekend if I get a chance.

**Comment by zacharyrs** [comment]
Should be sorted now - we'll have to see if anything else breaks...
