### ISSUE TITLE
Fan speed

### ISSUE THREAD

**Issue by gazelle-hub** [zacharyrs/ha-melview#4]
Hi there,

Again, great work on this component.

The Fan speed on my Heatpump and through the Melview App has 5 different speed settings.

Is that something easy to add/change to your component as it currently only has 3 speed settings.

Thanks
Adam

**Comment by gazelle-hub** [comment]
Sorry I should clarify, when I asked is that something easy to add/change I meant whether I could change it.

Thanks

**Comment by zacharyrs** [comment]
So honestly I haven't touched this in quite a while, so it's not quite at the top of my mind.

Just looking at the code, it should be a matter of adding the corresponding speeds under [here](https://github.com/zacharyrs/ha-melview/blob/master/melview.py#L68). You'll need to determine the corresponding numbers sent back to Melview - easiest done with the website and devtools. Let me know what they are too!

Unfortunately, it doesn't look like HomeAssistant has those speeds defined under its own [consts](https://github.com/home-assistant/core/blob/be56851feb29c33a1ec7fd12e867a4d0cdfa9d65/homeassistant/components/climate/const.py#L58), but you can just choose your own keys.

Looking back, the actual link to HomeAssistant ([climate.py](https://github.com/zacharyrs/ha-melview/blob/master/climate.py)) should use whatever modes are exposed by the custom part ([melview.py](https://github.com/zacharyrs/ha-melview/blob/master/melview.py)), so your changes should be picked up. I think HomeAssistant will pull the list of fan speeds from the linking file, so it should all work.

Note that I'll be changing the linking file per #3, so things might change again!

**Comment by gazelle-hub** [comment]
Hi there,

Sorry for the slow response.
I found that these are the settings for all of the different fan speeds.
Low = 1
Low-Medium = 2
Medium = 3
Medium-High = 5
High = 6

Kind of odd about the skipping a number but I've checked and these all seem to work. Managed to add these fan speeds by modifying the melview.py and defining the names and then setting the appropriate value.

**Comment by zacharyrs** [comment]
Closing this in favour of #5.
