### ISSUE TITLE
Dynamic fan speeds

### ISSUE THREAD

**Issue by zacharyrs** [zacharyrs/ha-melview#5]
Per #4, should get whatever fan speeds are available and expose them.

Website controller defines these with:
```js
self.fanStageInfo = {
  1: { class: "", ids: "5", desc: { 5: "On" } },
  2: { class: "ui-grid-a", ids: "25", desc: { 2: "Low", 5: "High" } },
  3: { class: "ui-grid-b", ids: "235", desc: { 2: "Low", 3: "Medium", 5: "High" } },
  4: { class: "ui-grid-c", ids: "2356", desc: { 2: "Low", 3: "Medium Low", 5: "Medium High", 6: "High" } },
  5: { class: "ui-grid-d", ids: "12356", desc: { 1: "Low", 2: "Medium Low", 3: "Medium", 5: "Medium High", 6: "High" } },
};

```

Gets the key in call to https://api.melview.net/api/unitcapabilities.aspx, we store under `self._caps.fanstage`.

Could expose using their speed names?

**Comment by gazelle-hub** [comment]
I've tried updating to this version but I only get 3 fan speeds even though I know that I definitely have 5 speeds.

I can see 5 speeds in the mobile app and I also had previously updated your old code to include the other 2 fan speeds (medium-low, medium-high).

**Comment by gazelle-hub** [comment]
When I go to https://api.melview.net/api/unitcapabilities.aspx I get:
{"error":"no data"}

**Comment by zacharyrs** [comment]
Oh I haven't implemented it yet - this is more just a thought process for when I have time to.
The latest changes were just to fix the warning about ClimateEntity per #3.

You won't get anything from the API as it needs a post request (see https://github.com/zacharyrs/ha-melview/blob/master/melview.py#L153).

**Comment by zacharyrs** [comment]
@gazelle-hub I have a potential fix for this in `dev`, feel free to switch to that branch and tell me if it works for you

**Comment by gazelle-hub** [comment]
Hi, sorry I haven't had a chance to get to this. My wife is WFH at the moment so I haven't been able to find much time to be on the computer. 

Should be able to get to it to test in the next couple of days.

**Comment by Taylor-Carnell** [comment]
@zacharyrs Can confirm, the 5 fan speeds from dev branch is working, changing speed is matched in the melview app/site and my super scientific, wind speed measuring paper plane on a string.

**Comment by zacharyrs** [comment]
Sorry, I've completely neglected this - I think I'll merge it over after #9.

**Comment by zacharyrs** [comment]
Closing as it's in https://github.com/zacharyrs/ha-melview/tree/dev - will do a big merge to master in #11.
