### ISSUE TITLE
Zone Support

### ISSUE THREAD

**Issue by MinaHany** [zacharyrs/ha-melview#9]
Hi,

Thanks for this it works great. I am close to getting zone support but need a tiny bit of help with a couple of things. 
How do I push my changes to a branch in the repo for you to review?

Thanks

**Comment by MinaHany** [comment]
Ok, I've gotten it to work. Changes are [here](https://github.com/MinaHany/ha-melview/pull/1/commits/7e6f1dce5735a56181bf84257a2981307cadd7f4).

It works but it is not very pretty. There are at least two things that need to be improved:
1) `switch.py` uses an additional instance of `MelView`. I'm not sure how to have the same instance shared by both `switch.py` and `climate.py`.
2) The configuration is duplicated atm. I am not sure how to share the login/pass between the two platforms.

**Comment by zacharyrs** [comment]
Hey, 

Thanks for this and sorry for not getting back to you sooner - I've been swamped with work and uni.

I think you've proposed the PR against your own repo, so it won't merge into this one - that said I've got a few suggested changes.
I've made some of these suggestions on your PR, so after you've looked over them I'd be keen for you to add a PR to this repo.

I'd also like to tackle extra `melview` - I'm guessing we need a unified `setup_platform` function somehow... I'll read into that and see.

Cheers!

**Comment by MinaHany** [comment]
No worries mate! I've addressed some of the feedback and commented on some other comments.
I've also raised a PR against this repo here: https://github.com/zacharyrs/ha-melview/pull/12

Yeah that unified setup_platform would be great. I tried googling a bit but didn't find anything...

**Comment by MinaHany** [comment]
Maybe we don't need a unified setup_platform actually. I think we just need a `class MelView` that memoises the response.

```
def get_devices_list(self):
    if self.response is None:
        self.response = requrests(...

    return self.response
```

**Comment by zacharyrs** [comment]
I did consider that, but I decided against it with the potential for having multiple MelView instances. 

I'm actually not too sure on how it'll behave now, but it's something I do want to support.
I think unifying it is definitely the most suitable option - especially when looking at some of the other plugins for HA.
There'll probably be a larger rewrite with #11 to get back on top of that all.

**Comment by zacharyrs** [comment]
Closing as current progress has been merged into https://github.com/zacharyrs/ha-melview/tree/dev (#14).
